/* Auto-generated by sync-landmarks.js - DO NOT EDIT MANUALLY */
window.EZREMS_LANDMARK_IMAGES = [
  "lotte-tower.jpg",
  "mangrove.jpg",
  "one-grove.png",
  "remarkvill.png",
  "starfield.jpg",
  "vl-lewest.jpg"
];
